language: rust
dist: xenial
cache:
  cargo: false
os:
  - linux
  - osx
  - windows
rust:
  - nightly
install:
  # Required for Racer autoconfiguration
  - rustup component add rust-src
  - rustup component add rust-analysis
script:
  # Since the rls-* subcrates use crates.io-based dependencies of themselves it
  # makes sense to test them in isolation rather than just RLS itself
  - cargo test -v --manifest-path rls-analysis/Cargo.toml
  - cargo test -v --manifest-path rls-blacklist/Cargo.toml
  - cargo test -v --manifest-path rls-data/Cargo.toml
  - cargo test -v --manifest-path rls-rustc/Cargo.toml
  - cargo test -v --manifest-path rls-span/Cargo.toml
  - cargo test -v --manifest-path rls-vfs/Cargo.toml
  - cargo build -v
  - cargo test -v
  - cargo test test_tooltip_std -- --ignored

env:
  global:
    - RUST_BACKTRACE=1
    - RLS_TEST_WAIT_FOR_AGES=1
    - CARGO_INCREMENTAL=0
