language: rust
dist: xenial
sudo: false
cache:
  cargo: false
os:
  - linux
  - osx
  - windows
rust:
  - nightly
install:
  # Required for Racer autoconfiguration
  - rustup component add rust-src
  - rustup component add rust-analysis
script:
  - cargo build -v
  - cargo test -v
  - cargo test test_tooltip_std -- --ignored
  # Since the rls-* subcrates use crates.io-based dependencies of themselves it
  # makes sense to test them in isolation rather than just RLS itself
  - (cd rls-analysis && cargo test -v)
  - (cd rls-blacklist && cargo test -v)
  - (cd rls-data && cargo test -v)
  - (cd rls-rustc && cargo test -v)
  - (cd rls-span && cargo test -v)
  - (cd rls-vfs && cargo test -v)

env:
  global:
    - RUST_BACKTRACE=1
    - RLS_TEST_WAIT_FOR_AGES=1
    - CARGO_INCREMENTAL=0

matrix:
  include:
    # - language: node_js
      services: xvfb
      before_install:
        # Somehow multi-language matrix.include doesn't play nicely with general
        # global/default settings (here rust: nightly) so install 10.5 ourselves
        # (otherwise it falls back to 0.10)
        - nvm install 10.5
        - curl https://sh.rustup.rs -sSf -m 60 | sh -s -- -y -v --default-toolchain stable
        - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then HOME="/c/Users/travis"; fi
        - export PATH="$HOME/.cargo/bin:$PATH"
        - cd editors/vscode
      install: npm install
      script: npm run ci:check
